services:
  traefik:
    image: traefik:latest
    container_name: ffb_traefik
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-network

  postgres:
    image: postgres:latest
    container_name: ffb_postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_config:/etc/postgresql/conf.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    shm_size: 128mb
    networks:
      - traefik-network
  
  backend:
    image: oven/bun:latest
    container_name: ffb_backend
    volumes:
      - ./backend/:/usr/src/app
    working_dir: /usr/src/app
    command: bun start
    depends_on:
      - postgres
    environment:
      - ACCESS_TOKEN_PRIVATE_KEY=${ACCESS_TOKEN_PRIVATE_KEY}
      - ACCESS_TOKEN_PUBLIC_KEY=${ACCESS_TOKEN_PUBLIC_KEY}
      - REFRESH_TOKEN_PRIVATE_KEY=${ACCESS_TOKEN_PRIVATE_KEY}
      - REFRESH_TOKEN_PUBLIC_KEY=${ACCESS_TOKEN_PUBLIC_KEY}
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-postgres}
      - FRONTEND_URL=${FRONTEND_URL:-http://127-0-0-1.sslip.io}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ffb-backend.rule=Host(`127-0-0-1.sslip.io`) && PathPrefix(`/api/v1`)'
      - "traefik.http.routers.ffb-backend.tls=true"
      - "traefik.http.routers.ffb-backend.entrypoints=websecure"
      - "traefik.http.routers.ffb-backend.service=ffb-backend"
      - "traefik.http.services.ffb-backend.loadbalancer.server.port=3000"
    networks:
      - traefik-network

  frontend:
    image: oven/bun:latest
    container_name: ffb_frontend
    volumes:
      - ./frontend/:/usr/src/app
    working_dir: /usr/src/app
    command: bun run dev.ts
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ffb-frontend.rule=Host(`127-0-0-1.sslip.io`)"
      - "traefik.http.routers.ffb-frontend.tls=true"
      - "traefik.http.routers.ffb-frontend.entrypoints=websecure"
      - "traefik.http.routers.ffb-frontend.service=ffb-frontend"
      - "traefik.http.services.ffb-frontend.loadbalancer.server.port=80"
    networks:
      - traefik-network

networks:
  traefik-network:
    driver: bridge

volumes:
  postgres_data:
  postgres_config:
