-- Creamos la base de datos.
CREATE DATABASE ffb_db;

-- Creamos el usuario para el dba.
CREATE USER ffb_admin WITH PASSWORD 'password_dba';
GRANT ALL PRIVILEGES ON DATABASE ffb_db TO ffb_admin;
\c ffb_db
GRANT ALL PRIVILEGES ON SCHEMA public TO ffb_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ffb_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ffb_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO ffb_admin;

-- Creamos el usuario para el backend.
CREATE USER ffb WITH PASSWORD 'password_backend';
GRANT CONNECT ON DATABASE ffb_db TO ffb;
\c ffb_db
GRANT USAGE ON SCHEMA public TO ffb;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ffb;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ffb;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ffb;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO ffb;
